-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Oxygen_Zion")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            size = 12,
        },
        rounding = 8,
    },
})

-- Bezier curves
hl.curve("quick", { type = "bezier", points = { {0.15, 0.0}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2.0,
    bezier = "quick",
    style = "slidefadevert",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 2.0,
    bezier = "quick",
    style = "slidefadevert",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 2.0,
    bezier = "quick",
    style = "slidefadevert",
})
